- passage à gnome-config

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4101,22 +4101,22 @@ fi
 
 
 
-  succeeded=no
+  succeeded=yes
 
-  if test -z "$PKG_CONFIG"; then
-    # Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
+  if test -z "$GNOME_CONFIG"; then
+    # Extract the first word of "gnome-config", so it can be a program name with args.
+set dummy gnome-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
 echo "configure:4111: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_PKG_CONFIG'+set}'`\" = set"; then
+if eval "test \"`echo '$''{'ac_cv_path_GNOME_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  case "$PKG_CONFIG" in
+  case "$GNOME_CONFIG" in
   /*)
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ac_cv_path_GNOME_CONFIG="$GNOME_CONFIG" # Let the user override the test with a path.
   ;;
   ?:/*)			 
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a dos path.
+  ac_cv_path_GNOME_CONFIG="$GNOME_CONFIG" # Let the user override the test with a dos path.
   ;;
   *)
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
@@ -4124,69 +4124,62 @@ else
   for ac_dir in $ac_dummy; do 
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_path_PKG_CONFIG="$ac_dir/$ac_word"
+      ac_cv_path_GNOME_CONFIG="$ac_dir/$ac_word"
       break
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  test -z "$ac_cv_path_GNOME_CONFIG" && ac_cv_path_GNOME_CONFIG="no"
   ;;
 esac
 fi
-PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
-if test -n "$PKG_CONFIG"; then
-  echo "$ac_t""$PKG_CONFIG" 1>&6
+GNOME_CONFIG="$ac_cv_path_GNOME_CONFIG"
+if test -n "$GNOME_CONFIG"; then
+  echo "$ac_t""$GNOME_CONFIG" 1>&6
 else
   echo "$ac_t""no" 1>&6
 fi
 
   fi
 
-  if test "$PKG_CONFIG" = "no" ; then
-     echo "*** The pkg-config script could not be found. Make sure it is"
-     echo "*** in your path, or set the PKG_CONFIG environment variable"
-     echo "*** to the full path to pkg-config."
-     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  if test "$GNOME_CONFIG" = "no" ; then
+     echo "*** The gnome-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the GNOME_CONFIG environment variable"
+     echo "*** to the full path to gnome-config."
+     echo "*** Or see http://www.freedesktop.org/software/gnomeconfig to get gnome-config."
+     succeeded=no
   else
-     PKG_CONFIG_MIN_VERSION=0.9.0
-     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo $ac_n "checking for  gnome gtk glib xml gdk_pixbuf ""... $ac_c" 1>&6
-echo "configure:4155: checking for  gnome gtk glib xml gdk_pixbuf " >&5
+      echo $ac_n "checking for  gnome gtk glib xml gdk_pixbuf ""... $ac_c" 1>&6
+echo "configure:4154: checking for  gnome gtk glib xml gdk_pixbuf " >&5
 
-        if $PKG_CONFIG --exists " gnome gtk glib xml gdk_pixbuf " ; then
-            echo "$ac_t""yes" 1>&6
-            succeeded=yes
-
-            echo $ac_n "checking GNOMELIBS_CFLAGS""... $ac_c" 1>&6
-echo "configure:4162: checking GNOMELIBS_CFLAGS" >&5
-            GNOMELIBS_CFLAGS=`$PKG_CONFIG --cflags " gnome gtk glib xml gdk_pixbuf "`
-            echo "$ac_t""$GNOMELIBS_CFLAGS" 1>&6
-
-            echo $ac_n "checking GNOMELIBS_LIBS""... $ac_c" 1>&6
-echo "configure:4167: checking GNOMELIBS_LIBS" >&5
-            GNOMELIBS_LIBS=`$PKG_CONFIG --libs " gnome gtk glib xml gdk_pixbuf "`
-            echo "$ac_t""$GNOMELIBS_LIBS" 1>&6
-        else
-            GNOMELIBS_CFLAGS=""
-            GNOMELIBS_LIBS=""
-            ## If we have a custom action on failure, don't print errors, but 
-            ## do set a variable so people can do so.
-            GNOMELIBS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors " gnome gtk glib xml gdk_pixbuf "`
-            echo $GNOMELIBS_PKG_ERRORS
-        fi
-
-        
-        
-     else
-        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
-        echo "*** See http://www.freedesktop.org/software/pkgconfig"
-     fi
+      echo $ac_n "checking GNOMELIBS_LIBS""... $ac_c" 1>&6
+echo "configure:4157: checking GNOMELIBS_LIBS" >&5
+      echo $ac_n "checking GNOMELIBS_CFLAGS""... $ac_c" 1>&6
+echo "configure:4159: checking GNOMELIBS_CFLAGS" >&5
+      for i in  gnome gtk glib xml gdk_pixbuf 
+	do
+	if $GNOME_CONFIG --cflags "$i" ; then
+	    GNOMELIBS_TMPCFLAGS=`$GNOME_CONFIG --cflags "$i"`
+	    GNOMELIBS_CFLAGS="GNOMELIBS_CFLAGS GNOMELIBS_TMPCFLAGS"
+	    
+	    GNOMELIBS_TMPLIBS=`$GNOME_CONFIG --libs "$i"`
+	    GNOMELIBS_LIBS="GNOMELIBS_LIBS GNOMELIBS_TMPLIBS"
+	else
+	    GNOMELIBS_CFLAGS=""
+	    GNOMELIBS_LIBS=""
+	    succeeded=no
+	    echo $GNOMELIBS_GNOME_ERRORS
+	fi
+      done
+      
+      
+      
   fi
 
   if test $succeeded = yes; then
      :
   else
-     { echo "configure: error: Library requirements ( gnome gtk glib xml gdk_pixbuf ) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." 1>&2; exit 1; }
+     { echo "configure: error: Library requirements ( gnome gtk glib xml gdk_pixbuf ) not met; consider adjusting the GNOME_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so gnome-config can find them." 1>&2; exit 1; }
   fi
 
 CFLAGS="$GNOMELIBS_CFLAGS"
@@ -4194,22 +4187,22 @@ LDFLAGS="$GNOMELIBS_LDFLAGS"
 
 APPLET="false"
 
-  succeeded=no
+  succeeded=yes
 
-  if test -z "$PKG_CONFIG"; then
-    # Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
+  if test -z "$GNOME_CONFIG"; then
+    # Extract the first word of "gnome-config", so it can be a program name with args.
+set dummy gnome-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4204: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_PKG_CONFIG'+set}'`\" = set"; then
+echo "configure:4197: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_GNOME_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  case "$PKG_CONFIG" in
+  case "$GNOME_CONFIG" in
   /*)
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ac_cv_path_GNOME_CONFIG="$GNOME_CONFIG" # Let the user override the test with a path.
   ;;
   ?:/*)			 
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a dos path.
+  ac_cv_path_GNOME_CONFIG="$GNOME_CONFIG" # Let the user override the test with a dos path.
   ;;
   *)
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
@@ -4217,63 +4210,56 @@ else
   for ac_dir in $ac_dummy; do 
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_path_PKG_CONFIG="$ac_dir/$ac_word"
+      ac_cv_path_GNOME_CONFIG="$ac_dir/$ac_word"
       break
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  test -z "$ac_cv_path_GNOME_CONFIG" && ac_cv_path_GNOME_CONFIG="no"
   ;;
 esac
 fi
-PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
-if test -n "$PKG_CONFIG"; then
-  echo "$ac_t""$PKG_CONFIG" 1>&6
+GNOME_CONFIG="$ac_cv_path_GNOME_CONFIG"
+if test -n "$GNOME_CONFIG"; then
+  echo "$ac_t""$GNOME_CONFIG" 1>&6
 else
   echo "$ac_t""no" 1>&6
 fi
 
   fi
 
-  if test "$PKG_CONFIG" = "no" ; then
-     echo "*** The pkg-config script could not be found. Make sure it is"
-     echo "*** in your path, or set the PKG_CONFIG environment variable"
-     echo "*** to the full path to pkg-config."
-     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  if test "$GNOME_CONFIG" = "no" ; then
+     echo "*** The gnome-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the GNOME_CONFIG environment variable"
+     echo "*** to the full path to gnome-config."
+     echo "*** Or see http://www.freedesktop.org/software/gnomeconfig to get gnome-config."
+     succeeded=no
   else
-     PKG_CONFIG_MIN_VERSION=0.9.0
-     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo $ac_n "checking for  applets ""... $ac_c" 1>&6
-echo "configure:4248: checking for  applets " >&5
+      echo $ac_n "checking for  applets ""... $ac_c" 1>&6
+echo "configure:4240: checking for  applets " >&5
 
-        if $PKG_CONFIG --exists " applets " ; then
-            echo "$ac_t""yes" 1>&6
-            succeeded=yes
-
-            echo $ac_n "checking GA_CFLAGS""... $ac_c" 1>&6
-echo "configure:4255: checking GA_CFLAGS" >&5
-            GA_CFLAGS=`$PKG_CONFIG --cflags " applets "`
-            echo "$ac_t""$GA_CFLAGS" 1>&6
-
-            echo $ac_n "checking GA_LIBS""... $ac_c" 1>&6
-echo "configure:4260: checking GA_LIBS" >&5
-            GA_LIBS=`$PKG_CONFIG --libs " applets "`
-            echo "$ac_t""$GA_LIBS" 1>&6
-        else
-            GA_CFLAGS=""
-            GA_LIBS=""
-            ## If we have a custom action on failure, don't print errors, but 
-            ## do set a variable so people can do so.
-            GA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors " applets "`
-            
-        fi
-
-        
-        
-     else
-        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
-        echo "*** See http://www.freedesktop.org/software/pkgconfig"
-     fi
+      echo $ac_n "checking GA_LIBS""... $ac_c" 1>&6
+echo "configure:4243: checking GA_LIBS" >&5
+      echo $ac_n "checking GA_CFLAGS""... $ac_c" 1>&6
+echo "configure:4245: checking GA_CFLAGS" >&5
+      for i in  applets 
+	do
+	if $GNOME_CONFIG --cflags "$i" ; then
+	    GA_TMPCFLAGS=`$GNOME_CONFIG --cflags "$i"`
+	    GA_CFLAGS="GA_CFLAGS GA_TMPCFLAGS"
+	    
+	    GA_TMPLIBS=`$GNOME_CONFIG --libs "$i"`
+	    GA_LIBS="GA_LIBS GA_TMPLIBS"
+	else
+	    GA_CFLAGS=""
+	    GA_LIBS=""
+	    succeeded=no
+	    
+	fi
+      done
+      
+      
+      
   fi
 
   if test $succeeded = yes; then
@@ -4514,7 +4500,6 @@ s%@GNOME_XML_CFLAGS@%$GNOME_XML_CFLAGS%g
 s%@GNOME_XML_LIB@%$GNOME_XML_LIB%g
 s%@EXTRA_GNOME_LIBS@%$EXTRA_GNOME_LIBS%g
 s%@EXTRA_GNOME_CFLAGS@%$EXTRA_GNOME_CFLAGS%g
-s%@PKG_CONFIG@%$PKG_CONFIG%g
 s%@GNOMELIBS_CFLAGS@%$GNOMELIBS_CFLAGS%g
 s%@GNOMELIBS_LIBS@%$GNOMELIBS_LIBS%g
 s%@GA_CFLAGS@%$GA_CFLAGS%g
